### ISSUE TITLE
Add support for `root` tool in getChangedPackages

### ISSUE THREAD

**Issue by Andarist** [changesets/bot#12]
It seems that there is no support for this so we always land here:
https://github.com/changesets/bot/blob/2fe1cd3e69856a1594cb8a308991ae43970fa182/index.ts#L187-L193

**Comment by mitchellhamilton** [comment]
Fixed this with beeb2fce3f40bb81d5d83ec0582f6c46557c2f7f and ea5c814d8d137f9f2fb3975d5a7744b8f80562a8
